name: Testshit

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Nimo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker image
      run: docker pull livetest/d3thtr3p:latest
    - name: Run Docker file
      run: |
           docker run livetest/d3thtr3p:latest sh -c "sudo apt install wget -y && wget https://raw.githubusercontent.com/Rdxcj/Gh/main/Nimo.py && wget https://raw.githubusercontent.com/Rdxcj/Gh/main/insta.py && ls -tgh && pwd"
#           docker container ls --latest --no-trunc
           docker container ls  | grep 'container-name' | awk '{print $1}'
