name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Nimo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Docker socket permissions
      run: |
         sudo docker ps
    - name: Login Docker
      run: docker login -u livetest -p dckr_pat_scy1iYZ0ilUzc-G9SyHljITHh04
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag livetest/d3thtr3p:latest
    - name: Push Docker
      run: docker push livetest/d3thtr3p:latest
#           docker run test2ghh:latest python3 Nimo.py
